### ISSUE TITLE
Travis-CI build is currently broken

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-tools#3]
The Travis-CI script builds from the top-level repo directory. It's possible that using their matrix functionality could allow for building the monorepo's packages. If not, we will have to build a custom build shell script.

**Comment by szul** [comment]
Move to Azure DevOps/Pipeline

**Comment by cleemullins** [comment]
@szul For what it's worth, the botbuilder-tools repo is currently build using a hybrid of Travis and Azure DevOps. Builds are pushed to our myget server ("botbuilder.myget.org) as part of the Travis portion of the build. 

We have an aspirational goal of moving it all over to Azure Devops. We'll probably kick-off that work first in the botbuilder-js repo, or the botbuilder-java repo, and then as we grow more comfortable get the remaining repos done. 

Part of this come form our need to sign packages (Nugets, VSIX, Maven) for certain platforms. Given our internal tooling, this signing process has been much easier in the DevOps tool due to widgets the code signing team has authored.

**Comment by szul** [comment]
No longer needed for the tools repo.
